apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
# namespace: prod
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Kubernetes Job"]
      restartPolicy: Never